parameters:
    translator.class: Liip\TranslationBundle\Translation\Translator

services:
    liip.translation.repository:
        class: Liip\TranslationBundle\Repository\UnitRepository
        arguments: ["%liip_translation_config%", "@translator", "@liip.translation.persistence", "@liip.translation.security"]

    liip.translation.security:
        class: Liip\TranslationBundle\Security\Security
        arguments: ["%liip_translation_config%"]

    liip.translation.persistence:
        class: %liip.translation.persistence.class%
        arguments: ["%liip.translation.persistence.options%"]

    liip.translation.loader:
        class: Liip\TranslationBundle\Translation\Loader
        arguments: ["@liip.translation.repository"]

    liip.translation.session_importer:
        class: Liip\TranslationBundle\Import\SessionImporter
        arguments: ["@liip.translation.repository", "@session", "@translator"]

    liip.translation.symfony_importer:
        class: Liip\TranslationBundle\Import\SymfonyImporter
        arguments: ["%liip_translation_config%", "@translator", "@liip.translation.repository"]

    liip.translation.exporter:
        class: Liip\TranslationBundle\Export\ZipExporter

    liip.xliff.loader:
        class: Liip\TranslationBundle\Translation\Loader\XliffFileLoader
